import Head from "next/head";
import { HeartIcon } from "@heroicons/react/solid";
import { signIn, signOut, useSession } from "next-auth/react";
import { useState } from "react";
export default function Home(props) {
  const { data: session, status } = useSession();
  return (
    <div className="w-full h-[100vh]">
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-full flex justify-center">
        <h1 className="ext-center flex font-semibold">
          Made By <HeartIcon className="animate-pulse w-5 mx-1 text-red-600" />{" "}
          with Osama
        </h1>
      </div>
      {session ? (
        <div className="w-full h-full flex items-center justify-center flex-col">
          <h1 className="font-bold m-5 text-4xl">you are sign in </h1>
          <button
            onClick={signOut}
            className=" hover:bg-black hover:text-white border-black border-2 px-2 py-1 font-semibold rounded-md"
          >
            Sign Out
          </button>
        </div>
      ) : (
        <div className="w-full h-full flex items-center justify-center">
          <button
            className="m-52 hover:bg-black hover:text-white border-black border-2 px-2 py-1 font-semibold rounded-md"
            onClick={signIn}
          >
            Sign in
          </button>
        </div>
      )}
    </div>
  );
}
